---
title: "Argument encoding in Evenki dialects"
author: "ANONYMIZED"
date: "2024-09-15"
output:
  html_document: default
  pdf_document: default
---

## Installing packages

```{r Installing, message=FALSE, warning=FALSE}
#R version: R 4.4.0
#install.packages("tidyverse") ##for tables and plots
library(dplyr)
library(tidyr)

#install.packages('cluster') ##for clustering: daisy()
library(cluster)

#install.packages("factoextra") ##for visualization: fviz_dend()
library("factoextra")

#install.packages('clValid') ##to test clusters
library(clValid)
#install.packages('pvclust')  ##to test clusters
library(pvclust)

```

## Preprocessing

### Raw Data

```{r RawData, message=FALSE, warning=TRUE}
setwd("C:/R_docs/EvenkiArg/final")
EvenkiArg<- read.csv("EvenkiArg_data.csv", header = TRUE)
View(EvenkiArg)

# Dataset 1: Corpus data
EvenkiArg %>% count(dialect, valency_pattern)-> EvenkiArg_corp ##counts the number of “valency_pattern” values (go_LOC, go_LAT, etc.) across dialects

EvenkiArg_corp %>%spread(valency_pattern, n, fill = 0) -> EvenkiArg_corp ##transforms into a new table: rows = dialects, columns = valency pattern values, cells = N of each valency pattern value in each dialect

View(EvenkiArg_corp)
write.csv(EvenkiArg_corp, file = 'EvenkiArg_corp_raw.csv') ##exports the table into a separate csv-file
write.table(EvenkiArg_corp, file = "EvenkiArg_corp_raw.txt", sep = "\t", row.names = FALSE, col.names = TRUE) ##exports into a separate txt-file

#Posterior corrections in Dataset 1 based on data from descriptions
EvenkiArg_corp[3, 8] = 0.5 ##Stony Tunguska: be_afraid_INS corrected according to descriptions ##The simulated normalized frequency was calculated as the 1/n | n is the total number of valency patterns of `be afraid´ attested for 'be afraid' across dialects = 1/3. Thus, its simulated absolute frequency was calculated as the sum of all uses of 'be afraid' in Stony Tunguska (1) divided to (n-1)=1/(3-1)=0.5.

View(EvenkiArg_corp)
write.csv(EvenkiArg_corp, file = 'EvenkiArg_corp.csv') ##exports the table into a separate csv-file
write.table(EvenkiArg_corp, file = "EvenkiArg_corp.txt", sep = "\t", row.names = FALSE, col.names = TRUE) ##exports into a separate txt-file

# Dataset 2 (expanded): Corpus & descriptions
# Data extracted from descriptions were added manually to table EvenkiArg_dialects_corp: the resulting table is EvenkiArg_dialects_all (NB data on Tokma-Lena and Nepa were corrected according to the corpus data, the column "source" was added)

EvenkiArg_all<- read.csv("EvenkiArg_all.csv", header = TRUE)
View (EvenkiArg_all)
```

### Normalized Data

```{r NormalizedData, message=FALSE, warning=TRUE}
EvenkiArg_all %>% mutate(ask_total = ask_ABL+ask_ACC+ask_DAT+ask_LAT, be_afraid_total=be_afraid_ABL+be_afraid_ACC+be_afraid_INS, come_total=come_ACC+come_DAT+come_LAT+come_LOC, go_total=go_ACC+go_DAT+go_LAT+go_LOC, help_total=help_ACC+help_DAT, leave_total=leave_ACC+leave_DAT+leave_LAT+leave_LOC, reach_total=reach_ACC+reach_DAT+reach_LOC, return_total=return_DAT+return_LAT+return_LOC, say_total=say_ACC+say_DAT+say_LAT+say_LOC)->EvenkiArg_all_norm #adds sum-columns for each verb

EvenkiArg_all_norm %>% mutate(ask_ABL=ask_ABL/ask_total, ask_ACC=ask_ACC/ask_total, ask_DAT=ask_DAT/ask_total, ask_LAT=ask_LAT/ask_total, be_afraid_ABL=be_afraid_ABL/be_afraid_total, be_afraid_ACC=be_afraid_ACC/be_afraid_total, be_afraid_INS=be_afraid_INS/be_afraid_total, come_ACC=come_ACC/come_total, come_DAT=come_DAT/come_total, come_LAT= come_LAT/come_total, come_LOC=come_LOC/come_total, go_ACC=go_ACC/go_total, go_DAT=go_DAT/go_total, go_LAT=go_LAT/go_total, go_LOC=go_LOC/go_total, help_ACC=help_ACC/help_total, help_DAT=help_DAT/help_total, leave_ACC=leave_ACC/leave_total, leave_DAT=leave_DAT/leave_total, leave_LAT=leave_LAT/leave_total, leave_LOC= leave_LOC/leave_total, reach_ACC=reach_ACC/reach_total, reach_DAT= reach_DAT/reach_total, reach_LOC=reach_LOC/reach_total, return_DAT=return_DAT/return_total, return_LAT= return_LAT/return_total, return_LOC=return_LOC/return_total, say_ACC=say_ACC/say_total, say_DAT= say_DAT/say_total, say_LAT= say_LAT/say_total, say_LOC= say_LOC/say_total) ->EvenkiArg_all_norm ##in each columns, changes the absolute number into percentages

EvenkiArg_all_norm %>% select(-c(ask_total, be_afraid_total, come_total, go_total, help_total, leave_total, reach_total, return_total, say_total))-> EvenkiArg_all_norm ##removes sum-columns

EvenkiArg_all_norm %>% mutate_all(~ifelse(is.nan(.), NA, .))->EvenkiArg_all_norm ##NaN to NA

# Dataset 1: Corpus data
EvenkiArg_corp_norm <- subset(EvenkiArg_all_norm,  source == "corp")
View(EvenkiArg_corp_norm)
write.csv(EvenkiArg_corp_norm, file='EvenkiArg_corp_norm.csv') ##exports into a separate csv-file
write.table(EvenkiArg_corp_norm, file = "EvenkiArg_corp_norm.txt", sep = "\t", row.names = FALSE, col.names = TRUE) ##exports into a separate txt-file


# Dataset 2: Corpus & descriptions
View(EvenkiArg_all_norm)
write.csv(EvenkiArg_all_norm, file='EvenkiArg_all_norm.csv') ##exports into a separate csv-file
write.table(EvenkiArg_all_norm, file = "EvenkiArg_all_norm.txt", sep = "\t", row.names = FALSE, col.names = TRUE) ##exports into a separate txt-file

```

## Clustering and visualization

### Dataset 1

```{r ClusteringCorp, message=FALSE, warning=TRUE}
EvenkiArg_corp_norm %>% select (-source)-> EvenkiArg_corp_norm_df ##removes non-necessary columns
EvenkiArg_corp_norm_df = data.frame(EvenkiArg_corp_norm_df, row.names = 'dialect')

EvenkiArg_corp_dist <- daisy(EvenkiArg_corp_norm_df, metric = "euclidean", stand = FALSE) ## distance matrix: using Euclidean metric; without standardization
round(EvenkiArg_corp_dist, 2)
summary(EvenkiArg_corp_dist) #to check whether there are NAs (no)
EvenkiArg_corp_hclust<-hclust(EvenkiArg_corp_dist, method = "complete") ## agglomerative hierarchical clustering, method "complete" compares the farthest neighbors in each pair of clusters (other methods give the same results: see below)
plot(EvenkiArg_corp_hclust)

# Testing the cluster solution

#Finding the optimal cluster solution from the dendrogram
##The largest vertical difference between nodes, a horizontal line in the middle of it. The number of vertical lines intersecting it == the optimal number of clusters
barplot(EvenkiArg_corp_hclust$height) #shows a height of each node
round(EvenkiArg_corp_hclust$height,3) #heights of nodes
jump_corp <-round(sapply(2:5, function(x) EvenkiArg_corp_hclust$height[x]-EvenkiArg_corp_hclust$height[x-1]),3)  #jumps between heights of nodes (right to left)
jump_corp
barplot(jump_corp) # 2 cl. > 3 cl. (chosen for visualization) > 5 cl. > 4 cl.

#Silhouette measure
##Shows the average well-formedness of the clusters in each solution (N of clusters): whether members of cl1 are close to each other and far from members of cl2
## A good result is > 0.2
silhouette_corp <- sapply(2:5, function(x) summary(silhouette(cutree(EvenkiArg_corp_hclust, k = x), EvenkiArg_corp_dist))$avg.width) ## for N of clusters from 2 to 5 
silhouette_corp
barplot(silhouette_corp)##the most reliable result is for 2 clusters (Taimyr vs. others); the 3-cluster solution, which is also ok, was chosen for visualization

# Dunn's index
## A measure of cluster compactness: discriminates clusters with larger intra-cluster variance and smaller inter-cluster variance
## The higher Dunn's index, the better
##Sensitive to noise in the data
dunn_test_corp <- sapply(2:5, function(x) dunn(distance = EvenkiArg_corp_dist, cutree(EvenkiArg_corp_hclust, k = x)))
dunn_test_corp
barplot(dunn_test_corp) #the results are similar for all cluster solutions, a bit higher for 2 clusters and 5 clusters (which is not good)

# Bootstrap re-sampling
##P-values: the closer to 1 the better, AU are more precise
EvenkiArg_corp_pvc <- pvclust(t(EvenkiArg_corp_norm_df), method.hclust = "complete", method.dist = "euclidean", nboot = 10000) #with the default nboot=1000, the result is unstable
plot(EvenkiArg_corp_pvc, hang = -1) ##groupings reliable with p>0.95: "all except for Taimyr"; "Barhahan & StonyTung"; the least reliable is "Yerbogachen&Sym"

# Visualization: 3 clusters
fviz_dend(EvenkiArg_corp_hclust, k = 3, cex = 0.8, horiz=TRUE, rect = TRUE, rect_border = "black", rect_lty = 1, lwd = 0.5, main = "Clustering based on argument encoding: Corpus data", k_colors = c("#A55926", "#26A559", "#5926A5"))

```

### Dataset 2

```{r ClusteringAll, message=FALSE, warning=TRUE}
EvenkiArg_all_norm %>% select (-source)-> EvenkiArg_all_norm_df ##removes non-necessary columns
EvenkiArg_all_norm_df = data.frame(EvenkiArg_all_norm_df, row.names = 'dialect')
View(EvenkiArg_all_norm_df)

EvenkiArg_all_dist <- daisy(EvenkiArg_all_norm_df, metric = "euclidean", stand = FALSE) ## distance matrix: using Euclidean metric; without standardization
round(EvenkiArg_all_dist, 2)
summary(EvenkiArg_all_dist)

EvenkiArg_all_hclust<-hclust(EvenkiArg_all_dist, method = "complete")
plot(EvenkiArg_all_hclust)

#Finding the optimal cluster solution from the dendrogram
barplot(EvenkiArg_all_hclust$height) #shows a height of each node
round(EvenkiArg_all_hclust$height,3) #heights of nodes
jump_all <- round(sapply(2:14, function(x) EvenkiArg_all_hclust$height[x]-EvenkiArg_all_hclust$height[x-1]),3)  #jumps between heights of nodes (right to left)
jump_all
barplot(jump_all)# 2 cl. > 6 cl. > ... (6 cl.-solution was chosen for visualization)

#Silhouette measure
silhouette_all <- sapply(2:14, function(x) summary(silhouette(cutree(EvenkiArg_all_hclust, k = x), EvenkiArg_all_dist))$avg.width) ## for N of clusters from 2 to 14 
silhouette_all
barplot(silhouette_all) ##2>3>6>7>8... the only reliable solutions are with 2 and 3 clusters (2-cluster solution is a bit more reliable, but less informative)

# Dunn's index
dunn_test_all <- sapply(2:14, function(x) dunn(distance = EvenkiArg_all_dist, cutree(EvenkiArg_all_hclust, k = x)))
dunn_test_all
barplot(dunn_test_all) #shows better results with the smallest uninformative clusters; 13 clusters is the best solution: 13>14>12>11>10>9>8>7>3>6... (6, chosen for visualization, is the first good middle-size cluster)

# Bootstrap re-sampling
EvenkiArg_all_pvc <- pvclust(t(EvenkiArg_all_norm_df), method.hclust = "complete", method.dist = "euclidean") ##NB some inappropriate matrices are generated and omitted
plot(EvenkiArg_all_pvc, hang = -1) ##

# Visualization: 3 clusters
fviz_dend(EvenkiArg_all_hclust, k = 3, cex = 0.8, horiz=TRUE, rect = TRUE, rect_border = "black", rect_lty = 1, lwd = 0.5, main = "Clustering based on argument encoding: Corpus data and data from descriptions", k_colors = c("#A55926", "#26A559", "#5926A5"))

# Visualization: 6 clusters (NB not reliable enough)
fviz_dend(EvenkiArg_all_hclust, k = 6, cex = 0.8, horiz=TRUE, rect = TRUE, rect_border = "black", rect_lty = 1, lwd = 0.5, main = "Clustering based on argument encoding: Corpus data and data from descriptions", k_colors = c("#7228A1", "#2894A1", "#57A128", "#A17228", "#A13528", "#E6B0AA"))

```

# Supplementary

## Testing different methods of clustering: Dataset 1

```{r DifferentClustMethods, message=FALSE, warning=TRUE}
#Hclust with 4 different methods: All give the same configuration
EvenkiArg_corp_hclust1<-hclust(EvenkiArg_corp_dist, method = "complete") #compares the farthest neighbours in all pairs of clusters
plot(EvenkiArg_corp_hclust1)
EvenkiArg_corp_hclust2<-hclust(EvenkiArg_corp_dist, method = "single") #compares the nearest neighbours in all pairs of clusters
plot(EvenkiArg_corp_hclust2)
EvenkiArg_corp_hclust3<-hclust(EvenkiArg_corp_dist, method = "average") #compares the average distances between all pairs of clusters
plot(EvenkiArg_corp_hclust3)
EvenkiArg_corp_hclust4<-hclust(EvenkiArg_corp_dist, method = "ward.D2") #minimizes the increase in the variance in the distances between the members of clusters
plot(EvenkiArg_corp_hclust4)

#Silhouette: The same results
silhouette_corp1 <- sapply(2:5, function(x) summary(silhouette(cutree(EvenkiArg_corp_hclust1, k = x), EvenkiArg_corp_dist))$avg.width)
silhouette_corp1 #0.4124825 0.2015429 0.1303219 0.1031998

silhouette_corp2 <- sapply(2:5, function(x) summary(silhouette(cutree(EvenkiArg_corp_hclust2, k = x), EvenkiArg_corp_dist))$avg.width)
silhouette_corp2 #0.4124825 0.2015429 0.1303219 0.1031998

silhouette_corp3 <- sapply(2:5, function(x) summary(silhouette(cutree(EvenkiArg_corp_hclust3, k = x), EvenkiArg_corp_dist))$avg.width)
silhouette_corp3 #0.4124825 0.2015429 0.1303219 0.1031998

silhouette_corp4 <- sapply(2:5, function(x) summary(silhouette(cutree(EvenkiArg_corp_hclust4, k = x), EvenkiArg_corp_dist))$avg.width)
silhouette_corp4 #0.4124825 0.2015429 0.1303219 0.1031998

#Dunn's test:
dunn_test_corp1 <- sapply(2:5, function(x) dunn(distance = EvenkiArg_corp_dist, cutree(EvenkiArg_corp_hclust1, k = x)))
dunn_test_corp1 #1.388207 1.021819 1.109536 1.428531

dunn_test_corp2 <- sapply(2:5, function(x) dunn(distance = EvenkiArg_corp_dist, cutree(EvenkiArg_corp_hclust2, k = x)))
dunn_test_corp2 #==

dunn_test_corp3 <- sapply(2:5, function(x) dunn(distance = EvenkiArg_corp_dist, cutree(EvenkiArg_corp_hclust3, k = x)))
dunn_test_corp3 #==

dunn_test_corp4 <- sapply(2:5, function(x) dunn(distance = EvenkiArg_corp_dist, cutree(EvenkiArg_corp_hclust4, k = x)))
dunn_test_corp4 #==

#Bootstrap re-sampling: similar results, the best results are for complete
EvenkiArg_corp_pvc1 <- pvclust(t(EvenkiArg_corp_norm_df), method.hclust = "complete", method.dist = "euclidean")
plot(EvenkiArg_corp_pvc1, hang = -1) #95,97,96,92

EvenkiArg_corp_pvc2 <- pvclust(t(EvenkiArg_corp_norm_df), method.hclust = "single", method.dist = "euclidean")
plot(EvenkiArg_corp_pvc2, hang = -1) #94,95,99,74 -- a bit worse

EvenkiArg_corp_pvc3 <- pvclust(t(EvenkiArg_corp_norm_df), method.hclust = "average", method.dist = "euclidean")
plot(EvenkiArg_corp_pvc3, hang = -1) #92, 95, 100, 84 -- a bit worse

EvenkiArg_corp_pvc4 <- pvclust(t(EvenkiArg_corp_norm_df), method.hclust = "ward.D2", method.dist = "euclidean")
plot(EvenkiArg_corp_pvc4, hang = -1) #90, 96, 98, 85 -- a bit worse
```

## Testing different methods of clusterization: Dataset 2

```{r DifferentClustMethods2, message=FALSE, warning=TRUE}
#Hclust with 4 different methods: all except for single look more or less logical
EvenkiArg_all_hclust1<-hclust(EvenkiArg_all_dist, method = "complete") #compares the farthest neighbours in all pairs of clusters
plot(EvenkiArg_all_hclust1) #Taimyr & Tommot left 
EvenkiArg_all_hclust2<-hclust(EvenkiArg_all_dist, method = "single") #compares the nearest neighbours in all pairs of clusters
plot(EvenkiArg_all_hclust2) #Taimyr>Tungir>Tommot -- very strange...
EvenkiArg_all_hclust3<-hclust(EvenkiArg_all_dist, method = "average") #compares the average distances between all pairs of clusters
plot(EvenkiArg_all_hclust3) #Taimyr>Tommot>Zeya
EvenkiArg_all_hclust4<-hclust(EvenkiArg_all_dist, method = "ward.D2") #minimizes the increase in the variance in the distances between the members of clusters
plot(EvenkiArg_all_hclust4) #Taimyr, Tommot right

#Silhouette: 3 clusters are reliable for complete and average, 2 clusters -- for single and ward.D2
silhouette_all1 <- sapply(2:14, function(x) summary(silhouette(cutree(EvenkiArg_all_hclust1, k = x), EvenkiArg_all_dist))$avg.width)
silhouette_all1 #0.26585989 0.21158362 vs. 0.10588037 0.08376357 0.16378202 0.16493518 0.16299020 0.15110707 0.11680909 0.09860804 0.09504543 0.07645824 0.04127993

silhouette_all2 <- sapply(2:14, function(x) summary(silhouette(cutree(EvenkiArg_all_hclust2, k = x), EvenkiArg_all_dist))$avg.width)
silhouette_all2 #0.27383240 vs. 0.11306008  0.10071506  0.05493615  0.05293707 -0.02884220  0.05110293  0.02439361 0.10789843  0.10714438  0.09504543  0.07645824  0.04127993 -- bad

silhouette_all3 <- sapply(2:14, function(x) summary(silhouette(cutree(EvenkiArg_all_hclust3, k = x), EvenkiArg_all_dist))$avg.width)
silhouette_all3 #0.27383240 0.21158362 vs. 0.12003155 0.08180147 0.15634626 0.16493518 0.16299020 0.15110707 0.11680909 0.09860804 0.09504543 0.07645824 0.04127993

silhouette_all4 <- sapply(2:14, function(x) summary(silhouette(cutree(EvenkiArg_all_hclust4, k = x), EvenkiArg_all_dist))$avg.width)
silhouette_all4 #0.26585989 vs. 0.15466843 0.14683099 0.17087782 0.16378202 0.16493518 0.16299020 0.15110707 0.11680909 0.10714438 0.09504543 0.07645824 0.04127993 -- bad

#Dunn's test: all the same -- 13 clusters is the best
dunn_test_all1 <- sapply(2:14, function(x) dunn(distance = EvenkiArg_all_dist, cutree(EvenkiArg_all_hclust1, k = x)))
dunn_test_all1 #0.6022684 0.6296056 0.4805451 0.4813759 0.6042610 0.6363244 0.6863944 0.8588228 0.8682279 0.9359655 1.0112998 !1.1737878! 1.1581980

dunn_test_all2 <- sapply(2:14, function(x) dunn(distance = EvenkiArg_all_dist, cutree(EvenkiArg_all_hclust2, k = x)))
dunn_test_all2 #0.6491666 0.5422652 0.6296056 0.5209102 0.5940511 0.5814864 0.5860571 0.5430618 0.7549096 0.8682279 1.0112998 !1.1737878! 1.1581980

dunn_test_all3 <- sapply(2:14, function(x) dunn(distance = EvenkiArg_all_dist, cutree(EvenkiArg_all_hclust3, k = x)))
dunn_test_all3 #0.6491666 0.6296056 0.5255633 0.5255633 0.5862193 0.6363244 0.6863944 0.8588228 0.8682279 0.9359655 1.0112998 !1.1737878! 1.1581980

dunn_test_all4 <- sapply(2:14, function(x) dunn(distance = EvenkiArg_all_dist, cutree(EvenkiArg_all_hclust4, k = x)))
dunn_test_all4 #0.6022684 0.4133936 0.4488338 0.4805451 0.6042610 0.6363244 0.6863944 0.8588228 0.8682279 0.8682279 1.0112998 !1.1737878! 1.1581980

#Bootstrap re-sampling: average is the best, complete -- a bit worse, but comparable
EvenkiArg_all_pvc1 <- pvclust(t(EvenkiArg_all_norm_df), method.hclust = "complete", method.dist = "euclidean")
plot(EvenkiArg_all_pvc1, hang = -1) #5 groups >= 90, 3 > 0.95

EvenkiArg_all_pvc2 <- pvclust(t(EvenkiArg_all_norm_df), method.hclust = "single", method.dist = "euclidean")
plot(EvenkiArg_all_pvc2, hang = -1) #4 groups >= 90

EvenkiArg_all_pvc3 <- pvclust(t(EvenkiArg_all_norm_df), method.hclust = "average", method.dist = "euclidean")
plot(EvenkiArg_all_pvc3, hang = -1) # 6 groups >= 90, 3 > 0.95

EvenkiArg_all_pvc4 <- pvclust(t(EvenkiArg_all_norm_df), method.hclust = "ward.D2", method.dist = "euclidean")
plot(EvenkiArg_all_pvc4, hang = -1) # 4 groups >= 90
```
